### ISSUE TITLE
HA integration with EK fails with "Received invalid token data."

### ISSUE THREAD

**Issue by conorboyd** [mikey0000/ha-electric-kiwi#10]
Hi,

Really like the idea of integrating my EK account with HA, thanks.

When trying to add the integration to my HA installation (running in a Docker container on Synology NAS), I get prompted to log in to my EK account, then get the confirmation from Nabu Casa that it's successfully authenticated and I can close the window, but on returning to HA, it tells me "Received invalid token data.".

Any workarounds, or is this a known issue?

Thanks,

Conor

**Comment by mikey0000** [comment]
Hi there

Yeah I encountered this recently so something must have changed on EK's end perhaps. I'm off for the holidays but will take a look when I'm back. The integration still functions after a reload so you should be fine till then.

**Comment by conorboyd** [comment]
Thanks for the reply, all good.

It's a blocker for me though since it's the initial first-time installation of your integration that fails.

Separate Q: does your integration pull usage (eg PV export data) from EK as well?

**Comment by mikey0000** [comment]
Pulling that data has been on the to do list, I'll try and start work on it in the new year or so, I've got some other changes I need to make too.

**Comment by mikey0000** [comment]
> Thanks for the reply, all good.
> 
> It's a blocker for me though since it's the initial first-time installation of your integration that fails.
> 
> Separate Q: does your integration pull usage (eg PV export data) from EK as well?

If your able to find any useful logs on the error that would be great.

**Comment by conorboyd** [comment]
Not obvious, no, sorry.

**Comment by mikey0000** [comment]
Update: Issue is with Electric Kiwi, I've opened an issue on their github today.

**Comment by mikey0000** [comment]
https://github.com/electrickiwi-nz/api-samples/issues/21 should be resolved soon.

**Comment by ebw44** [comment]
It seems to be resolved.
Reloading the integration (or restarting Home Assistant) was not enough for me, I had to click the "Add Hub" to reauthenticate with electric kiwi.

PS: The time without the integration working made us realize how much this integration is useful, so thanks a lot for the great work.

**Comment by ebw44** [comment]
For the last couple of days I had issues with the connection to electric kiwi. Initially I got the error `Failed setup, will retry: 500, message='Internal Server Error', url='https://account-link.nabucasa.com/refresh_token/electric_kiwi' `
After removing and reinstalling the integration (with a few restart of HA) I now have the error
`Failed setup, will retry: Error request failed: 403`.
It seems vaguely related to this issue, but if not let me know and I'll open a new one.

**Comment by conorboyd** [comment]
Yep, same with me.

Have not removed and reinstalled yet.

**Comment by mikey0000** [comment]
Sorry guys there's some changes going on, on the EK side and I need to make some changes, this happened very fast and was out of my control. Will be fixed when it's fixed which should be this coming week

**Comment by conorboyd** [comment]
No worries, thanks for the update!

**Comment by mikey0000** [comment]
please follow the issue tracker here for those that use the integration with core

https://github.com/home-assistant/core/issues/136545

**Comment by aklnlh** [comment]
Just saying thanks for the integration, appreciate the effort you put in developing it.

**Comment by ebw44** [comment]
Should I try commit 39aed1c ?

**Comment by mikey0000** [comment]
Latest commit on this repository should work.

**Comment by PaulCavill** [comment]
@mikey0000 FYI  the new HACS version looks to be missing some of the migration code.

![Image](https://github.com/user-attachments/assets/73ae1368-9c2a-436f-9b73-723116387d8c)

**Comment by mikey0000** [comment]
Fixed, thanks for pointing that out

5 Feb 2025 10:27:51 pm PaulCavill ***@***.***>:

**Comment by ebw44** [comment]
With version 0.9.2 when trying to change the "Hour of free power" I get the error `TypeError: Dict key must a type serializable with OPT_NON_STR_KEYS` (full log below).
The core integration still works for me.

```
2025-02-07 10:34:24.205 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472427651808] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 188, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/electric_kiwi/select.py", line 74, in async_select_option
    await self.coordinator.async_update_hop(value)
  File "/config/custom_components/electric_kiwi/coordinator.py", line 103, in async_update_hop
    self.async_set_updated_data(await self.ek_api.post_hop(hop_interval))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/electrickiwi_api/api.py", line 157, in post_hop
    post_hop = await self.auth.request("post", ElectricKiwiEndpoint.hourofpower_by_connection.format(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
                                       json=data)
                                       ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/electrickiwi_api/auth.py", line 43, in request
    return await self._websession.request(method, url, **kwargs, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 521, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/payload.py", line 448, in __init__
    dumps(value).encode(encoding),
    ~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/json.py", line 162, in json_dumps
    return json_bytes(data).decode("utf-8")
           ~~~~~~~~~~^^^^^^
TypeError: Dict key must a type serializable with OPT_NON_STR_KEYS
```

**Comment by mikey0000** [comment]
Fixed, thanks for the find! Have also PR'ed into core as well

**Comment by mikey0000** [comment]
2025.2.1 is now out with the updated api.
